aws_region            = "eu-central-1"
profile               = "airflow"
environment           = "dev"
cluster_name          = "airflow-cluster"
kubernetes_version    = "1.29"
vpc_cidr              = "10.20.0.0/16"
availability_zones    = ["eu-central-1a", "eu-central-1b"]
private_subnet_cidrs  = ["10.20.1.0/24", "10.20.2.0/24"]
public_subnet_cidrs   = ["10.20.101.0/24", "10.20.102.0/24"]
node_instance_types   = ["t3.medium"]
desired_nodes         = 2
min_nodes             = 1
max_nodes             = 3
rds_instance_class    = "db.t3.micro"
rds_allocated_storage = 20
database_name        = "airflow"
database_user        = "airflow_admin"
database_secret_name  = "airflow-cluster-database-password"
database_password     = null
